# Generated by Django 4.2.6 on 2024-03-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('product', models.CharField(max_length=122)),
                ('mobile', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=122)),
                ('about_product', models.TextField()),
            ],
        ),
    ]
