# Generated by Django 4.2.6 on 2024-03-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('product', models.CharField(max_length=122)),
                ('mobile', models.TextField()),
                ('location', models.CharField(max_length=122)),
                ('quantity', models.CharField(max_length=122)),
                ('about_product', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='login',
            old_name='name',
            new_name='Username',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='product',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
        migrations.RemoveField(
            model_name='login',
            name='about_product',
        ),
        migrations.RemoveField(
            model_name='login',
            name='location',
        ),
        migrations.RemoveField(
            model_name='login',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='login',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=300),
        ),
    ]
