# Generated by Django 4.2.6 on 2024-03-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_receiver_rename_name_login_username_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='receiver',
            new_name='donor',
        ),
    ]
